### ISSUE TITLE
Installation from PyPI does not work even on Linux Systems

### ISSUE THREAD

**Issue by crgnam** [ceres-navigation/ceres-raytracer#25]
Reported by another user:  Installation from PyPI failed with the following error:

```
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpx42x5zg4 build_wheel /tmp/tmpvg3h09vq
       cwd: /tmp/pip-install-ezfj7baw/ceres-raytracer
  Complete output (87 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-38
  creating build/lib.linux-x86_64-cpython-38/crt
  copying crt/entity.py -> build/lib.linux-x86_64-cpython-38/crt
  copying crt/passes.py -> build/lib.linux-x86_64-cpython-38/crt
  copying crt/cameras.py -> build/lib.linux-x86_64-cpython-38/crt
  copying crt/render.py -> build/lib.linux-x86_64-cpython-38/crt
  copying crt/lighting.py -> build/lib.linux-x86_64-cpython-38/crt
  copying crt/static.py -> build/lib.linux-x86_64-cpython-38/crt
  copying crt/__init__.py -> build/lib.linux-x86_64-cpython-38/crt
  copying crt/rotations.py -> build/lib.linux-x86_64-cpython-38/crt
  running build_ext
  -- The CXX compiler identification is GNU 9.4.0
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Could NOT find pybind11 (missing: pybind11_DIR)
  CMake Error at src/CMakeLists.txt:2 (pybind11_add_module):
    Unknown CMake command "pybind11_add_module".


  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-ezfj7baw/ceres-raytracer/build/temp.linux-x86_64-cpython-38/_crt/CMakeFiles/CMakeOutput.log".
  /tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/dist.py:531: UserWarning: Normalizing '0.5a' to '0.5a0'
    warnings.warn(tmpl.format(**locals()))
  Traceback (most recent call last):
    File "/tmp/tmpx42x5zg4", line 280, in <module>
      main()
    File "/tmp/tmpx42x5zg4", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpx42x5zg4", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 244, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, _file_, 'exec'), locals())
    File "setup.py", line 128, in <module>
      setup(
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 136, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-1p3l77sy/overlay/lib/python3.8/site-packages/setuptools/command/build_ext.py", line
```

**Comment by crgnam** [comment]
added `pybind11-global` as installation requirement
